src/internal.h, src/interpreter.c, src/vm.c, src/vm.h, tests/Makefile, tests/test.mk, tests/unit_test.c, v7.c
Implemented with longjmp for the recursive interpreter.
DIFFBASE=#99
=> Implement exception handling

src/internal.h, src/interpreter.c, src/vm.c, src/vm.h, tests/Makefile, tests/test.mk, tests/unit_test.c, v7.c
Various numerical and logical operators and compound assign operations
DIFFBASE=#100
=> Implement more operators

src/internal.h, src/interpreter.c, src/vm.c, src/vm.h, tests/Makefile, tests/test.mk, tests/unit_test.c, v7.c
And fix property assignment w.r.t to prototypes.
DIFFBASE=#101
=> Implement post- and pre- (de|in)crements

src/internal.h, src/interpreter.c, src/vm.c, src/vm.h, tests/Makefile, tests/test.mk, tests/unit_test.c, v7.c
=> Added `void()` and `typeof`

src/interpreter.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
=> Added `cond`, `in`, `return`, `throw`

src/interpreter.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
=> Implement `delete` operator

src/api.c, src/internal.h, src/interpreter.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
=> Implement `this`

src/api.c, src/internal.h, src/interpreter.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
=> Implement `new`

src/error.c, src/internal.h, src/interpreter.c, src/object.c, src/sources.mk, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
Improve equality operators and add enough primitives to being able to check
for inheritance relationships
=> Implement instanceof and core error objects

src/boolean.c, src/internal.h, src/interpreter.c, src/object.c, src/sources.mk, src/vm.c, src/vm.h, tests/unit_test.c, v7.c, v7.h
This PR also changes `v7_cfunction_t` signature to the agreed one
=> Add Boolean ctor

src/internal.h, src/interpreter.c, tests/unit_test.c, v7.c
ECMA tests coverage: 3.01% -> 4.95%
=> Implement `catch` variable binding

src/object.c, src/vm.c, tests/unit_test.c, v7.c
=> Implement `keys()` and `getOwnPropertyNames()`

src/interpreter.c, src/object.c, src/vm.c, tests/unit_test.c, v7.c
=> Implement `for in`

src/interpreter.c, src/object.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
ECMA tests coverage: 13.17%, yay!
DIFFBASE=#151
=> Implement Object.defineProperty et al

src/interpreter.c, src/object.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
ECMA tests coverage: 15.90%
DIFFBASE=#154
=> Implement `Object.defineProperties()`

src/interpreter.c, src/object.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
=> Honour non writable and non configurable props

tests/unit_test.c
ECMA tests coverage: 99.61%
Obviously this means that now most of the tests run somehow
but we are not using the real driver so we are not checking
the reported errors.
=> Fix error reporting

src/math.c, src/object.c, src/sources.mk, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
=> Port Math object

examples/Makefile, examples/load_json_config/Makefile, examples/load_json_config/config.json, examples/load_json_config/load_json_config.c, src/interpreter.c, src/math.c, src/object.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c, v7.h
Export v7_to_* functions
Fix #121
=> Add load_json_config example

src/interpreter.c, src/object.c, src/slre.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c, v7.h
=> Add `v7_set` and hide `v7_set_property`

src/interpreter.c, src/string.c, tests/unit_test.c, v7.c
DIFFBASE=189
Fix String.charCodeAt().
=> Hardcode String/Number prototype lookup

src/object.c, v7.c
=> Fix `Object` vs `Object.prototype` bug

src/interpreter.c, src/vm.c, tests/ecma_report.txt, tests/unit_test.c, v7.c
As outlined in go/v7-getsetters
=> Implement array indirection for get/setters

src/interpreter.c, tests/ecma_report.txt, v7.c
And also if `valueOf` is the result of a getter invocation.
=> Call valueOf even if it's a JS function

src/boolean.c, src/interpreter.c, src/number.c, src/object.c, src/string.c, src/vm.c, tests/ecma_report.txt, v7.c
=> Add toString method

src/boolean.c, src/interpreter.c, src/number.c, src/object.c, src/string.c, src/vm.c, tests/ecma_report.txt, v7.c
=> Fix toFixed

src/interpreter.c, src/number.c, tests/ecma_report.txt, v7.c
=> Fix Number ctor

src/interpreter.c, src/object.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
This is a cleanup. Coverage unchanged.
=> Remove redundant functions

src/internal.h, src/interpreter.c, tests/ecma_report.txt, tests/unit_test.c, v7.c
=> Implement labeled continue

src/gc.c, src/gc.h, src/sources.mk, src/vm.c, v7.c
Factor out allocations for fixed size structs.
=> Add GC skeleton

src/internal.h, src/interpreter.c, src/string.c, v7.c
Also cleans up c90 compiler warning
=> Cleanup. Remove defunct abort jmp buf

src/gc.c, src/gc.h, src/vm.c, tests/unit_test.c, v7.c
Fix arena name (useful for debugging)
=> Cleanup GC

src/date.c, src/internal.h, src/object.c, src/sources.mk, src/vm.c, src/vm.h, tests/ecma_report.txt, tests/unit_test.c, v7.c
Date class is implemented in this pull request. Should close #132
Rebased source edition.
Marco's comments from #258 is incorporated.
=> 15.9 Date Objects - implementation

CPPLINT.cfg, src/date.c, src/interpreter.c, src/math.c, src/object.c, src/parser.c, src/slre.c, src/string.c, src/vm.c, src/vm.h, v7.c, v7.h
Also let the linter less strict about multiple statements
per line. In several places it would be awkward to blindly follow
that rule.
=> Cleanup style

src/function.c, src/internal.h, src/sources.mk, src/vm.c, src/vm.h, tests/ecma_report.txt, v7.c
=> Add Function ctor

src/interpreter.c, tests/ecma_report.txt, v7.c
=> Prohibit deleting vars in strict mode

src/array.c, src/interpreter.c, tests/ecma_report.txt, v7.c
=> Add Array.prototype.splice()

src/date.c, v7.c
MinGW support
Closes https://github.com/cesanta/v7/issues/281
=> MinGW support

src/interpreter.c, v7.c
---
Hi @cpq, please review this change. Thanks
=> Unwind the tmp stack on longjmp

tests/unit_test.c
Warnings due to -fsanitize=undefined
=> Remove last warnings

Makefile, src/gc.h, src/sources.mk, src/stdlib.c, src/vm.c, src/vm.h, tests/ecma_report.txt, v7.c
=> Embed JS stdlib code

src/interpreter.c, src/string.c, src/vm.c, tests/ecma_report.txt, v7.c
Hi @cpq, I would like you to review this small change. Thanks
=> Fix integer overflow

Makefile, circle.yml, tests/.gitignore, tests/Dockerfile, tests/test.mk
Hi @cpq, please review this small change.
We'd better ensure 32-bit mode works even without fighting with windows
=> Add 32-bit build

.gitignore, src/CPPLINT.cfg, src/array.c, src/function.c, src/interpreter.c, src/main.c, src/stdlib.c, src/string.c, src/vm.c, tests/unit_test.c, v7.c
This is preparation work for refactoring the definition of val_t
---
Hi @cpq, please review this cleanup PR
=> Reduce surface of direct manipulation of val_t

tests/test.mk
Hi @alashkin, I'd like to you do a teeny-tiny code review, thanks
=> Fix minor issue in test.mk

src/interpreter.c, src/tokenizer.c, src/vm.c, v7.c
http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Loops_and_Switch_Statements
---
Hi @alashkin, please review this long but style only PR.
It contains no semantic changes.
=> Abide by our styleguide on blocks in switch cases

src/gc.h, src/interpreter.c, src/tokenizer.c, src/vm.c, tests/ecma_report.txt, v7.c
DIFFBASE=#304
---
Hi @cpq, please goto review this PR
=> Remove dependency on GCC ext to cleanup tmp stack

src/vm.c, tests/ecma_report.txt, v7.c
=> Fix 32bit s_concat behavior

src/internal.h, src/interpreter.c, src/math.c, src/vm.c, tests/ecma_report.txt, v7.c, v7.h
=> Fix mingw build

src/array.c, src/boolean.c, src/date.c, src/function.c, src/interpreter.c, src/number.c, src/object.c, src/stdlib.c, src/string.c, src/vm.c, src/vm.h, tests/ecma_report.txt, v7.c
Also remove spurious arguments to array's `pop`.
DIFFBASE=#320
=> Add `length` getter to functions

src/stdlib.c, tests/ecma_report.txt, v7.c
=> Add Array.prototype.shift()

src/vm.c, tests/ecma_report.txt, tests/test.mk, v7.c
Reduce merge conflicts and makes it easier to see 
which tests changed status.
=> Improve ecma report stability

src/function.c, src/gc.c, src/internal.h, src/stdlib.c, src/vm.c, tests/ecma_report.txt, v7.c
=> Add Function.prototype.apply()

src/ast.c, src/vm.c, src/vm.h, tests/ecma_report.txt, tests/unit_test.c, v7.c
Add special tag for strings that are exactly 5 bytes long.
Fix #327.
=> Add V7_TAG_STRING_5

src/gc.c, src/internal.h, src/number.c, src/vm.c, src/vm.h, tests/test.mk, v7.c
Design document at http://go.cesanta.com/compacting-gc
DIFFBASE=#333
=> Implement compacting GC for strings

src/gc.c, v7.c
---
Addressed last review comments
(but PR was merged before pushing them).
=> Cleanup compacting GC

src/stdlib.c, src/vm.c, src/vm.h, tests/ecma_report.txt, tests/unit_test.c, v7.c
Hi @alashkin, please make a review! Since @mmikulicic is off today, let this PR take over PR #336
=> Limit array size to 2^32 

src/interpreter.c, tests/unit_test.c, v7.c
=> Remove dead code

examples/load_json_config/load_json_config.c, src/array.c, src/boolean.c, src/date.c, src/function.c, src/interpreter.c, src/json.c, src/math.c, src/number.c, src/object.c, src/regex.c, src/stdlib.c, src/string.c, src/vm.c, src/vm.h, tests/ecma_report.txt, tests/unit_test.c, v7.c, v7.h
v7_array_at -> v7_array_get
v7_array_append -> v7_array_push
Added v7_array_set
=> Rename array functions

src/array.c, src/stdlib.c, tests/ecma_report.txt, v7.c
DIFFBASE=341
Bumps coverage by few bits.
=> Sanitize Array indexOf and lastIndexOf

src/stdlib.c, tests/ecma_report.txt, v7.c
=> Add Function.prototype.call

src/interpreter.c, v7.c
=> Add small optimization for i_value_of

src/interpreter.c, tests/ecma_report.txt, v7.c
Simplify and minor performance improvements
DIFFBASE=#360
=> Improve string to number conversion

Makefile, src/vm.c, tests/unit_test.c, v7.c, v7.h
=> Apply clang-format to v7.h

src/object.c, tests/ecma_report.txt, v7.c
=> Respect second arg of Object.create()

README.md, src/object.c, src/vm.c, src/vm.h, tests/ecma_report.txt, v7.c
=> Add Object.{preventExtensions,isExtensible}

docs/ReleaseNotes.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/374)
=> Add skeleton for release notes

.clang-format, Makefile, src/array.c, src/ast.c, src/ast.h, src/boolean.c, src/date.c, src/function.c, src/gc.c, src/gc.h, src/interpreter.c, src/json.c, src/main.c, src/math.c, src/mbuf.c, src/number.c, src/object.c, src/parser.c, src/regex.c, src/slre.c, src/stdlib.c, src/string.c, src/tokenizer.c, src/varint.c, src/vm.c, src/vm.h, tests/unit_test.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/372)
=> Update clang-format to 3.6

tests/unit_test.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/375)
=> Format unit_test.c

src/interpreter.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/382)
=> Fix compilation error on Arduino DUE

src/json.c, src/object.c, src/vm.c, src/vm.h, tests/ecma_report.txt, v7.c
Hi @alashkin , please make a review.
This bumps coverage to 50.94%.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/385)
=> Small Object.defineProperty enhancement

src/internal.h, src/socket.c, src/sources.mk, src/stdlib.c, src/vm.h, tests/unit_test.c, v7.c
Hi, @mmikulicic 
In order to keep reasonable size of PR I've created this one with socket basics.
It contain only initialization, ctor, close and bind (bind - as first fucntion)
Please, make review for me.
Pay attention on:
1. Usage of `v7_create_foreign`
2. Creation of "namespaces" constants (Type.SOCK_STREAM) - lines 182-204
Thank you.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/384)
=> Sockets: init, ctor, close() and bind()

src/socket.c, tests/unit_test.c, v7.c
Hi, @mmikulicic 
Next portion of sockets: 3 functions - listen, send & connect.
Thank you.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/386)
=> Sockets: listen, send, connect

Makefile, tests/Dockerfile
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/383)
=> Update v7_test docker image to use clang 3.6

src/array.c, src/interpreter.c, src/object.c, src/regex.c, src/string.c, src/vm.c, v7.c
Preparatory for optimized dense arrays
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/387)
=> Use array accessors when accessing arrays

src/vm.c, src/vm.h, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/388)
=> Rewrite more array accessors using array API

src/internal.h, src/socket.c, src/stdlib.c, tests/unit_test.c, v7.c
Hi, @cpq 
Please, review this PR.
I don't have Windows now - I've relied on appveyor, which was removed, as I understand.
I gonna install Wine & MSVC6, but now - if you don't mind - check with it, please.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/389)
=> Add ifdefs to sockets

src/socket.c, tests/unit_test.c, v7.c
Hi, @cpq
I've removed `trunc()`
Thank you!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/390)
=> MSVC6 fix - trunc removed

src/array.c, tests/ecma_report.txt, v7.c
ECMA coverage at 51.75%
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/393)
=> Fix Array.map and Array.every index type

src/interpreter.c, src/vm.c, src/vm.h, v7.c
Cleanup and helpers
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/396)
=> Address #394 review comments

Makefile, src/internal.h, src/regex.c, src/string.c, src/vm.c, tests/Makefile, v7.c, v7.h
resault ECMA test:
section 15.5 +11 testcases
section 15.10 +209 testcases
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/395)
=> correct Str_match(), Str_replace(), Str_search(), Str_split(), Regex_exec()

src/vm.c, src/vm.h, v7.c
See go.cesanta.com/v7-prop-iter, this implements alternative API 4.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/398)
=> Property iteration helper

src/string.c, tests/unit_test.c, v7.c, v7.h
Save ecma results as they are happening on linux/osx
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/401)
=> Cleanup format and regexp

circle.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/408)
=> Make benchmark docker image build optional

src/vm.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/406)
=> Make leak detector happy

tests/unit_test.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/409)
=> Fix unit test build on win32

src/vm.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/407)
=> Fix strict aliasing warnings

src/socket.c, tests/unit_test.c, v7.c
Sorry for PR size. In order to replace exceptions with retvals I had to make a little refactoring and as result PR contains a lot of small changes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/410)
=> Implement low level Socket interface

tests/Dockerfile
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/411)
=> Add watcom compiler to our build docker image

src/date.c, src/internal.h, src/interpreter.c, src/js_stdlib.c, src/math.c, src/number.c, src/socket.c, src/vm.c, tests/ecma_report.txt, tests/unit_test.c, v7.c
discovered when trying it out with the watcom complier
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/412)
=> Fix portability issues

src/regex.c, src/socket.c, src/stdlib.c, src/string.c, tests/unit_test.c, v7.c
Partially addresses #371
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/414)
=> Add a V7_DISABLE_REGEX

Makefile, scripts/platform.mk, src/date.c, src/internal.h, src/interpreter.c, src/main.c, src/vm.c, tests/ecma_report.txt, tests/unit_test.c, v7.c
DIFFBASE=415
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/416)
=> Fix on VS 2013, closes #348

tests/Dockerfile
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/418)
=> Add windows compilers to build docker image

src/socket.c, tests/ecma_report.txt, v7.c
Hi, @mmikulicic.
Please, review this small PR.
Closes #417
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/420)
=> Fixed warnings on Linux

Makefile, circle.yml, make.sh, scripts/platform.mk, tests/Dockerfile, tests/Makefile, tests/dobuild, tests/test.mk
And enable windows build on CircleCI
DIFFBASE=419
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/422)
=> Ship VC6 inside our docker build image

src/internal.h, src/interpreter.c, src/slre.c, tests/unit_test.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/421)
=> Fix (or work around) GCC warnings

src/interpreter.c, src/slre.c, src/slre.h, src/vm.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/426)
=> Really disable regexp support

src/slre.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/424)
=> correct 're_match: backtrack overflow!' problem in some ECMA tests

src/string.c, v7.c
+12 test-cases in section 15.5 of ECMA tests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/428)
=> correct String_ctor()

src/ast.c, src/ast.h, src/interpreter.c, src/string.c, v7.c
Hi @alashkin, I'd like you to code do this small but noisy code review, thanks.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/430)
=> Reduce storage size of aux AST table

src/function.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/429)
=> redesign Function_ctor()

src/os.c, src/sources.mk, src/stdlib.c, src/vm.h, tests/unit_test.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/433)
=> OS interface: renaming File interface

docs/build.md, src/function.c, tests/Dockerfile, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/432)
=> Add some docs about the build infrastructure

src/internal.h, src/interpreter.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/437)
=> Remove useless strings from binary

src/function.c, src/interpreter.c, v7.c
Found while trying some sunspider benchmark
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/435)
=> Fix missing recording GC temp root

scripts/platform.mk
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/434)
=> Fix LLVM symbolizer path

src/array.c, src/function.c, src/json.c, src/object.c, src/os.c, src/vm.c, src/vm.h, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/438)
=> Drop num_args argument in set_cfunc_obj_prop

src/internal.h, src/os.c, tests/unit_test.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/440)
=> Add OS.rename and OS.uname methods.

benchmark/Dockerfile-base, benchmark/bench.sh, benchmark/serve.R
And remove obsolete dependencies
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/439)
=> Fix benchmark graph labels

src/internal.h, src/os.c, tests/unit_test.c, v7.c
Deleted code is the best code. Fixes #441 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/444)
=> Drop OS.uname

src/main.c, v7.c
Squashes a warning.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/450)
=> Handle fread() failure in read_file

src/crypto.c, src/sources.mk, src/stdlib.c, src/vm.h, tests/unit_test.c, v7.c
Fixes #136
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/452)
=> Port old Crypto interface to the new API

src/vm.h, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/447)
=> Add comment explaining NaN-packing

scripts/platform.mk
#459
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/462)
=> Old versions of gmake don't support undefine

src/ast.c, src/ast.h, src/main.c, tests/unit_test.c, v7.c, v7.h
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/461)
=> Expose v7_compile() to public

scripts/gen-features-full.pl, src/features_full.h, src/features_medium.h, src/math.c, src/stdlib.c, v7.c
Minor fix to feature gen script.
#442
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/464)
=> Split Math into features

src/utf.c, src/utf.h, v7.c
Leave only the functions currently used.
#371
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/466)
=> Reduce UTF library footprint to the bare minimum

src/date.c, src/features_full.h, src/features_medium.h, src/interpreter.c, src/regex.c, src/slre.c, src/slre.h, src/stdlib.c, src/string.c, src/vm.c, tests/unit_test.c, v7.c
#371
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/460)
=> V7_DISABLE_REGEX -> V7_ENABLE__RegExp

src/features_full.h, src/features_medium.h, src/utf.c, src/utf.h, tests/unit_test.c, v7.c
This breaks some Unicode-related ECMA tests but we'll deal with those
later, when specifying profiles.
#371
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/467)
=> Make UTF support optional

Makefile
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/468)
=> Have "all" target build all V7 profiles

src/vm.c, v7.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/471)
=> Squash the last warning when compiling V7

tests/Dockerfile-build
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/473)
=> Fix wine on docker image

src/main.c, src/vm.c, tests/ecma_report.txt, v7.c
It was returning the number of bytes actually written to the buffer,
which is not what other code expects.
Fixes #402
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/474)
=> Make to_str return the number of bytes needed

benchmark/Dockerfile-base, benchmark/bench.sh, benchmark/bench_props.js, benchmark/bench_str.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/475)
=> Use valgrind massive to measure heap usage

docs/api.adoc, docs/internals.adoc, v7.c, v7.h
Add internals.adoc too
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/476)
=> Add C/C++ docs section

examples/uno/Makefile, v7.c, v7.h
Small style fix.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/477)
=> Fix make clean

examples/.gitignore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/478)
=> Ignore build artifacts for example

circle.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/484)
=> Remove CircleCI config

examples/.gitignore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/488)
=> Remove .gitignore files from V7 public repo

Makefile
Closes #570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/572)
=> Fix test runner flags
