- src/util.c
- v7.c
Before:
% time ./v7 fib.js
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597,
2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418,
317811, 514229, 832040]
7049123
./v7 fib.js  71,47s user 0,13s system 99% cpu 1:11,85 total
After:
% time ./v7 fib.js
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597,
2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418,
317811, 514229, 832040]
7049123
./v7 fib.js  42,39s user 0,08s system 99% cpu 42,573 total
Compiled with gcc 4.8 using
% gcc -O3 -g -DNDEBUG -DV7_EXE v7.c -o v7 -lm
> Optimize `cmp` function.

- src/ast.c
- src/ast.h
- src/interpreter.c
- src/vm.c
- src/vm.h
- tests/unit_test.c
- v7.c
Note: call frames are not yet linked together so each function can only
access it's own variables.
DIFFBASE=#95
> Implement function call

- src/api.c
- src/internal.h
- src/interpreter.c
- src/main.c
- src/vm.c
- src/vm.h
- tests/ecma_driver.js
- tests/unit_test.c
- v7.c
- v7.h
DIFFBASE=96
This is a sketch for the C/JavaScript glue API.
Added print() function to the global object for debugging.
Switched command line utility from v7_exec to v7_exec_2 - that is the beginning of wiping out old functionality.
Imlemented VAR_DECL
> Add C functions support

- src/interpreter.c
- src/vm.c
- src/vm.h
- tests/Makefile
- tests/test.mk
- tests/unit_test.c
- v7.c
Implement function invokation scope as chain
of frames chained via the __proto__ field, so that
variables from outer lexical scopes are looked up
via the same mechanism as object property lookup.
Fix prototype name comparison.
Allow ECMA test sandboxing so that unit test doesn't crash
when we enable a codepath that triggers an interpreter bug.
(disabled by default, enable in tests/Makefile)
> Traverse prototype chain

- src/ast.c
- src/interpreter.c
- tests/unit_test.c
- v7.c
Interpreter was using wrong AST base address.
Add asserts in `ast` so it won't happen again.
Use `sigsetjmp`, which is more valgrind friendly and way faster.
Fallback to `setjmp` on Windows.
> Fix function call invocation

- src/interpreter.c
- tests/unit_test.c
- v7.c
Currently `./v7 -e ''` evaluates to some random number.
> Evaluate empty input to V7_NULL

- src/internal.h
- src/interpreter.c
- src/main.c
- src/parser.c
- src/parser.h
- src/sources.mk
- tests/Makefile
- tests/unit_test.c
- v7.c
Minor refactorings:
- Pass `v7` to `parse()`
> Rename `aparser` to `parser`

- Makefile
- src/ast.c
- src/internal.h
- src/interpreter.c
- src/vm.c
- src/vm.h
- tests/test.mk
- tests/unit_test.c
- v7.c
- v7.h
Added $(realpath) to makefiles to let IDE know the exact file location to jump to compilation errors.
Fixed warning in interpreter.c
Exported creation functions to v7.h
> Split v7_create_value to type-specific functions

- src/interpreter.c
- tests/unit_test.c
- v7.c
Arguments where evaluated after `this` had been already switched
to the value seen by the callee.
> Fix `this`

- src/error.c
- src/internal.h
- src/interpreter.c
- src/math.c
- src/object.c
- src/vm.c
- tests/ecma_driver.js
- tests/unit_test.c
- v7.c
Fix driver, it was actually failing but misreported.
Fix a few bugs revealed now that ecma tests work:
Fix string concat when buffer gets relocated and
inline strings.
Fix string escaping for \", \' and \ + real newline
(used in multiline strings).
Fix to_string buffer overflow.
> Throw real errors

- src/error.c
- src/internal.h
- src/interpreter.c
- src/main.c
- src/object.c
- src/parser.c
- src/parser.h
- src/vm.c
- tests/unit_test.c
- v7.c
- v7.h
Now values and execution status are separate, allowing
both undefined values to be returned and exceptions not
inheriting from `Error` to be thrown and recognized as
such.
> Fix `v7_exec` API

- src/array.c
- src/interpreter.c
- src/string.c
- src/vm.c
- tests/ecma_report.txt
- v7.c
This fix reduces coverage, because SUDDENLY loops in tests start to work!  (e.g. `for (i =0; i < arr.length; i++`)
> Implement {String,Array}.prototype.length

- src/boolean.c
- src/internal.h
- src/interpreter.c
- src/number.c
- src/object.c
- src/string.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- v7.c
* Fix infinite recursion when throwing an exception while
constructing an exception object to throw.
* Fix property attributes for important properties
and move constants to the `Number` object and not in the number prototype.
* Define `MAX_VALUE` and `MIN_VALUE` according to the spec.
* Fix rendering of Infinity numbers and use a sprintf precision
that matches more closely the rules in:
http://www.ecma-international.org/ecma-262/5.1/#sec-9.8.1
so that more test are excercised (although it's not perfect).
* Hack ordering of `Object.keys()`, in order to pass some tests were
unlocked by other fixes.
> Fix Number conversion and arithmetics

- circle.yml
- tests/update_hist_ecma_report.sh
Can be seen quickly by picking the last build in
https://circleci.com/gh/cesanta/v7/tree/master
and opening the "artifacts" tab.
> Generate history graph of ecma test reports

- examples/load_json_config/Makefile
- src/interpreter.c
Fix the compile. And also fix a typo in evaluation of AST_NE_NE. There's a & where a && is intended.
> Fix ast ne ne

- src/interpreter.c
- v7.c
Regression introduced in cdecb21a4fd
when all conversions included an implicit potential
call to `valueOf()`.
Thanks to @giannitedesco for spotting this.
> Fix evaluation order of some numeric binary ops

- src/string.c
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
Also reorders ecma and interpreter tests, so that regressions
can be cought faster.
> Invoke valueOf on to_string conversions

- src/interpreter.c
- v7.c
There is some not too nice repetition here, to be cleaned up.
> Fix `arguments` array build on `v7_apply`

- src/interpreter.c
- src/parser.c
- tests/ecma_report.txt
- v7.c
* on `with` in strict mode
* on duplicate object literal properties
> Throw some syntax errors in strict mode

- src/internal.h
- src/interpreter.c
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
Labeled breaks are with the same longjmp mechanism used for exceptions.
> Implement labeled break

- src/array.c
- src/interpreter.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
When a setter is found in the prototype chain, it should
be invoked. Array `length` property should also have a setter.
This fixes a couple of flacky tests which added an owned
property by assigning `length` to arrays thus breaking our
quicky&dirty array sort/reverse.
> Fix setter invocation and add `length` setter

- src/interpreter.c
- v7.c
I didn't see a test case fail for this, but without it
can potentially lure the optimizer to do something like #244
> Add volatile to setjmp result

- src/vm.c
Clang's MSAN was complaining about unitialized memory.
It might caused by a failure to instrument `stpncpy`
since AFAIK the only difference between it and `strncpy`
is the return value which is ignored here.
> Make MSAN not complain about strings

- tests/.gitignore
- tests/Dockerfile
- tests/test.mk
MSAN currently only supports linux,
The docker image hence needs the llvm-symbolizer tool.
> Add make rule to run tests under MSAN

- src/parser.c
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
Invalid var expressions such as `var p = [`
were reported as successfully parsed but the
generated AST contained junk nodes.
> Fix parsing of invalid var initializers

- Makefile
- src/array.c
- src/internal.h
- src/slre.c
- src/string.c
- src/vm.c
- tests/unit_test.c
- v7.c
- Fix incestuous string insertion in Str_split and added comment
- Fix arg_long with zero length strings
- Fix bounds in SLRE
- Initialize flags in SLRE.
MSAN also doesn't instrument correctly stpncpy so changing with strncpy.
DIFFBASE=#0x100
> Fix uninitialized memory access

- src/string.c
- v7.c
We cannot pass a buffer backed by a string mbuf to
v7_create_tring. For now let's create a temporary buffer.
> Fix String.trim

- src/array.c
- src/interpreter.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- v7.c
Add `length` property to CFUNCTION object, which must be the number of arguments.
Respect sorting function argument in `Array.prototype.sort`
Coverage increases to 32.90%
> Implement Array.prototype.join

- src/gc.c
- src/gc.h
- src/internal.h
- src/interpreter.c
- src/mm.h
- src/sources.mk
- src/vm.c
- src/vm.h
- tests/Dockerfile
- tests/unit_test.c
- v7.c
V7_ENABLE_GC will enable the simple fixed sized GC
described in http://go.cesanta.com/v7-gc
TODO(in progress):
- Compacting GC with relocation
- fix tmp stack unwind on exception catch
(it's pure luck it works now)
I'd like to pipeline the review for the GC
starting with this chunk.
> Add GC arenas and sweeping

- src/function.c
- v7.c
Handles:
```js
new Function(new String("a,b"), "c", new String("return a+b+c"))
```
> Allow String wrappers to be passed to Function

- src/function.c
- tests/unit_test.c
- v7.c
Not sure exactly which pointer to the stack buffer is kept
but it looks like avoiding the var works around it.
TODO(mkm) investigate
> Fix Function ctor mem use after return

- src/gc.c
- v7.c
This regression slipped through while addressing
a review comment in #264
> Fix arena init

- tests/Makefile
> Add MSAN make rule

- src/array.c
- src/gc.c
- src/string.c
- src/vm.c
- tests/ecma_report.txt
- v7.c
- Handle NaN and infinites in string and array functions
- Sort uses lexical ordering by default, as required by the standard.
This incidentally fixes a undefined behavior in converting infinites and NaN
to integer
- Fix unaligned memory access when dereferencing a foreign string pointer
encoded in the foreign string mbuf.
> Fix undefined behaviour

- src/date.c
- tests/unit_test.c
- v7.c
Clang ASAN was issuing runtime warnings that the `%03*s` format
is not supported. The OSX C library's implementation does support it
though, but it might not be portable.
Furthermore, this solution fixes a couple of illegal inputs that were
previously accepted erroneously:
- `IncDec 01 2015 00:00:00`
- `My Jul 01 2015 00:00:00`
---
@alashkin, I'd like you to review this small change. Thanks.
> Fix date parsing and avoid using `%03*s`

- src/interpreter.c
- v7.c
v7_apply can be invoked from user/builtin C code.
Usually the argument array will be a temporary object
and hence the GC will free it.
It's unreasonable to force all call sites to add the
argument array to the tmp_stack.
---
Hi @cpq,
Please review my micronian change. Thanks.
This fixes the issue you found in #291
> Add v7_apply args to GC rootset

- src/gc.c
- src/gc.h
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
Cleanup (UN)MARK(ED) macros and use a more self-documenting approach
for accessing the first pointer of a GC cell.
---
Hi @cpq, please tell me whether this is more readable
and maintanable than the previous mess.
> Enhance readability of GC code

- Makefile
- src/ast.h
- src/date.c
- src/gc.c
- src/gc.h
- src/internal.h
- src/interpreter.c
- src/math.c
- src/mm.h
- src/vm.c
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
- v7.h
Re-enable GC.
Fix short strings behavior on 32-bit archs (strings were truncated because of the implicit pointer conversion).
> Restore build on MSVC6

- src/array.c
- src/boolean.c
- src/date.c
- src/interpreter.c
- src/number.c
- src/object.c
- src/string.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- v7.c
Functions are objects, but since all functions point to the same function
prototype, we don't represent it. In the same position as the object's prototype,
v7_function had the scope pointer, thus this was the object traversed when
accessing function properties.
> Fix function prototype access

- src/string.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- v7.c
The fix revealed that string method have to convert `this`
to string (or it will segfault).
The same change is in the regexp branch by @vrz.
> Fix access to builtin prototypes

- src/boolean.c
- src/date.c
- src/number.c
- src/string.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- v7.c
Extract common code for creating a constructor in C,
adapt builtin objects constructors and fix mixup of constructor
and prototype methods in `date`.
> Remove special casing for C constructors

- CPPLINT.cfg
- Makefile
- src/ast.h
- src/boolean.c
- src/gc.c
- src/interpreter.c
- src/number.c
- src/parser.c
- src/stdlib.c
- src/string.c
- src/vm.c
- tests/ecma_report.txt
- tests/test.mk
- tests/unit_test.c
- v7.c
Also re-enables a disabled test and fixes
a spurious invocation of cpplint.
> Cleanup obsolete TODO comments and style

- src/internal.h
- src/interpreter.c
- src/vm.c
- src/vm.h
- v7.c
The goal of this small change is to avoid allocating strings
every time a function gets called (arguments property) or an array
or function (closure) object gets created (prototype, constructor properties)
This is not a replacement for a proper string interning solution TBD.
> Implement predefined strings

- src/object.c
- src/vm.c
- src/vm.h
- v7.c
Short strings are compared by val_t value
DIFFBASE=#367
---
@cpq, this doesn't currently buy much (~6% of the whole ecma test run),
it can be improved by passing down the val_t of the key if known (usually it is if
the lookup is performed by the VM, as opposed by the user who passes a char *).
> Improve property string comparison

- benchmark/Dockerfile
- benchmark/Dockerfile-base
- benchmark/Makefile
CircleCI doesn't have docker image caching, this avoid
refetching common ubuntu packages on every build
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/378)
> Split base image from benchmark image

- src/error.c
- src/gc.c
- src/internal.h
- src/interpreter.c
- src/number.c
- src/stdlib.c
- tests/ecma_report.txt
- v7.c
New'ed C constructors are now called with `this`'s prototype
correctly set to the prototype defined in the C function object
prototype property (for those C constructors that are also function objects).
This makes it simpler to write C constructors and enables reusing the same
C constructor function for a whole inhertiance tree (e.g. error objects)
ECMA coverage up to 50.92 %
Small performance improvement
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/379)
> Refactor C constructors and error objects

- src/array.c
- src/boolean.c
- src/date.c
- src/function.c
- src/internal.h
- src/interpreter.c
- src/number.c
- src/object.c
- src/regex.c
- src/string.c
- src/vm.c
- v7.c
It doesn't require exec-ing every time an internal exception is raised
DIFFBASE=#379
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/380)
> Create exceptions with C code

- src/gc.c
- v7.c
This fixes an issue with uninitialized v7_object::attribute
The attribute was introduced in #370 and was not cleared.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/381)
> Clear all cells returned by GC

- src/socket.c
- tests/unit_test.c
- v7.c
Winsock wants `struct sockaddr_in :: sin_family ` set, otherwise `connect()` fails with error 10049 (WSAEADDRNOTAVAIL).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/391)
> Fix Socket.connect() on MSVC6

- benchmark/bench_arr.js
- src/array.c
- src/gc.c
- src/gc.h
- src/internal.h
- src/interpreter.c
- src/mm.h
- src/number.c
- src/object.c
- src/regex.c
- src/string.c
- src/vm.c
- src/vm.h
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
Not yet ready to be the default array type. ECMA test performance has not
been measurably improved, but array intensive real world application have
(benchmark added to PR where V7 is finally faster than MUJS at something)
Most failing tests were incorrectly passing before.
DIFFBASE=#393
---
This PR is quite rough. Didn't feel like postponing too much the first round of comments,
but there is much code repetition and stuff can be factored out. The most ugly thing is the 
repeated `for .. in` implementation. I don't know if it make sense to implement some kind of 
generic iterator so that we can iterate over all keys (migh be useful in some other place).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/394)
> Add dense arrays: initial implementation

- Makefile
- scripts/platform.mk
- src/internal.h
- src/interpreter.c
- src/vm.c
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
It also fixes 0/0 on other platforms and reverts 5d30094
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/413)
> Fix msvc6 build, floats

- Makefile
- scripts/platform.mk
- src/internal.h
- src/interpreter.c
- src/vm.c
- tests/ecma_report.txt
- tests/unit_test.c
- v7.c
By disabling ECMA tests which are utterly broken on VC6 right now, but this
enables us to run VC6 builds and tests regularly
DIFFBASE=413
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/415)
> Make VC6 build and test pass

- Makefile
- make.sh
- scripts/platform.mk
- tests/Dockerfile
- tests/Makefile
- tests/dobuild
- tests/test.mk
Usage:
TL;DR: `make` for local build, `./make.sh` for dockerized build. In future
advanced builds will be available only through `./make.sh` wrapper.
- was:
make docker
is:
./make.sh
- was:
docker run --rm -v $PWD/..:/cesanta -v $HOME/Build/vc6:/vc6 -t -i cesanta/v7_test -C tests test_asan TEST_FILTER=inter
is:
./make.sh -C tests test_asan TEST_FILTER=inter
This is a step of the incremental simplification of our makefile:
- add a wrapper that will execute make via am ephemeral docker container
passing all the arguments
- simplify by removing all pseudo targets that invoke other rules via the
docker client.
they didn't work well anyway because env were not passed down
TODO: refactor our makefiles so that they perform simple builds everywhere
and delegate all the complicated stuff (asan, …
> Add makefile wrapper for docker

- src/internal.h
- src/os.c
- tests/unit_test.c
- v7.c
And fix conditional compilation on Windows.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/443)
> Revert "Make OS.uname useful even on non-POSIX platforms."

- circle.yml
This way if the difftest passes, we are sure that the src/ sources
and the amalgamation are in sync and hence we can trust more
the subsequent compilation errors.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/445)
> Run difftest as first thing

- src/interpreter.c
- src/slre.c
- v7.c
Squashes the "argument might be clobbered by longjmp" warnings.
Both instances were benign.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/454)
> Mark a couple vars volatile to make GCC happy

- scripts/platform.mk
It was written to be able to disable some gcc specific warnings,
but it turns out that we don't want to disable them anymore.
However, it might be useful soon for other kind of compiler specific flags,
and it turned out to be a >15m task so I'd spare it to the next guy.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/455)
> Add a make variable that detects gcc vs clang

- src/slre.c
- v7.c
Found with clang's -fsanitize=undefined.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/456)
> Fix signed int overflow in SLRE

- scripts/gen-features-full.pl
- src/features_full.h
- src/features_medium.h
- src/features_minimal.h
- src/internal.h
- src/sources.mk
- src/v7_features.h
- v7.c
So it can be included into files that do not otherwise need internal.h.
Why not features.h? Because of /usr/include/features.h.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/458)
> Pull out feature-related stuff into v7_features.h

- .hooks/commit-msg
- Makefile
- scripts/platform.mk
Otherwise do nothing, fall back on the checked-in version.
This commit also includes a change to the commit hook that wouldn't
accept the summary which is exactly 50 chars long :)
Fixes #457.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/459)
> Only generate features_full.h if Perl is available

- examples/uno/Makefile
- examples/uno/uno.ino
- src/date.c
- src/features_minimal.h
- src/internal.h
- src/main.c
- src/vm.c
- tests/unit_test.c
- v7.c
* Move some includes down to modules where they are used
* Disable date-related functions in minimal profile
Result is still way too big:
Sketch uses 110,568 bytes (342%) of program storage space. Maximum is
32,256 bytes.
Global variables use 5,281 bytes (257%) of dynamic memory, leaving
-3,233 bytes for local variables. Maximum is 2,048 bytes.
#442
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/v7/472)
> Initial work to make V7 minimal compile for UNO
